language: android

jdk:
 - oraclejdk7

android:
  components:
    - build-tools-22.0.1
    - android-22

script:
  - ./gradlew clean check -Dpre-dex=false

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.gradle
    
notifications:
  email: false
  
sudo: false
